blog/urls.py
from django.urls import re_path, path
from .views import (
    create_blog_view, blog_details_view,
    update_blog_post_view, delete_blog_post
    )

app_name = 'blog'

urlpatterns = [
    re_path(r'^create_post/$', create_blog_view, name="create_blog_post"),
    path('<slug>/', blog_details_view, name="blog_details"),
    path('<slug>/edit', update_blog_post_view, name="update_blog_post"),
    path('<slug>/delete', delete_blog_post, name="delete_blog_post"),
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.conf import settings 
from django.db.models.signals import pre_save, post_delete
from django.dispatch import receiver
from ckeditor.fields import RichTextField


def upload_location(instance, filename):
    """Generate the file path for image upload"""
    file_path = f'blog/{str(instance.author.id)}/{str(instance.title)}-{filename}'
    return file_path

class BlogPost(models.Model):
    """Creates these fields in the database which will all be the attributes of a post"""
    title                   = models.CharField(max_length=50, blank=False, null=False)
    body                    = RichTextField(max_length=10000, blank=False, null=False)
    # body                    = models.TextField(max_length=10000, blank=False, null=False)
    image                   = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published          = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated            = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author                  = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug                    = models.SlugField(blank=True, unique=True, max_length=255)


    def __str__(self):
        return self.title

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    """Deletes the image of a blog-post when the correlating BlogPost is deleted"""
    instance.image.delete(False)


def pre_save_blog_post_receiver(sender, instance, **kwargs):
    """Checks if a blog post has a slug, if not it creates one. This executes before each blog post is commited to the database"""
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)
pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)


blog/forms.py
from django import forms
from .models import BlogPost


class CreateBlogPostForm(forms.ModelForm):
    class Meta():
        model = BlogPost
        fields = ('title', 'body', 'image')
    instance = ""
class UpdateBlogPostForm(forms.ModelForm):
    class Meta():
        model = BlogPost

        fields = ('title', 'body', 'image')

    def save(self, commit=True):
        blog_post = self.instance
        blog_post.title = self.cleaned_data.get('title')
        blog_post.body = self.cleaned_data.get('body')
        
        if self.cleaned_data['image']:
            blog_post.image = self.cleaned_data.get('image')

        if commit:
            blog_post.save()

        return blog_post

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.db.models import Q
from .forms import (CreateBlogPostForm,
                    UpdateBlogPostForm
                    )
from account.models import Account
from .models import BlogPost

from blog.models import (
    BlogPost
)
from django.views.generic import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.utils import timezone
from random import shuffle
# Create your views here.

def create_blog_view(request):
    """The view to create a blog post"""
    if not request.user.is_authenticated:
        return redirect ('must_auth')
    context = {}

    user = request.user
    create_blog_form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if create_blog_form.is_valid():
        obj = create_blog_form.save(commit=False)
        author = Account.objects.filter(email=user.email).first() # Return a queryset '.first' gets the first item there
        obj.author = author
        obj.save()
        context['success_message'] = f"'{obj.title}' has been posted."
        create_blog_form = CreateBlogPostForm()
        return redirect('home_page')
    else:
        create_blog_form = CreateBlogPostForm()
    context['create_blog_form'] = create_blog_form
    return render(request, 'blog/create_blog.html', context)


def blog_details_view(request, slug):
    """The view to get the details of a blog"""
    context = {}
    blog_details = get_object_or_404(BlogPost, slug=slug)
    # blog_posts = BlogPost.objects.all()[:3]
    # blog_posts = sorted(BlogPost, key=attrgetter('date_updated'), reverse=True)[:5]
    blog_posts = BlogPost.objects.filter(date_published__lte=timezone.now()).order_by('?')[:3]
    context['blog_post'] = blog_posts
    context['blog_details'] = blog_details
    return render(request, 'blog/blog_details.html', context)


def update_blog_post_view(request, slug):
    """The view to update a blog post"""
    context = {}
    user = request.user
    if not user.is_authenticated:
        redirect('must_auth')

    blog_post = get_object_or_404(BlogPost, slug=slug)

    if user != blog_post.author:
        return HttpResponse("<h3>You are not the author of this post!</h3>")

    if request.method == 'POST':
        update_form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
        if update_form.is_valid():
            update_form.save()
            context['success_message'] = f"'{blog_post.title}' has been updated."
            return redirect('home_page')

    # else:
    update_form = UpdateBlogPostForm(instance=request.user, initial = {
                "title": blog_post.title,
                "body": blog_post.body,
                "image": blog_post.image,
        })

    context['blog_post'] = blog_post
    context['update_form'] = update_form
    return render(request, 'blog/edit_blog_post.html', context)

def get_blog_queryset(query=None):
    """The view that performs the search functionality"""
    queryset = []
    queries = query.split(" ") # To remove the whitespaces between queries
    for query in queries:
        posts = BlogPost.objects.filter(
            Q(title__icontains=query) | Q(body__icontains=query)
        ).distinct()

        for post in posts:
            queryset.append(post)

    return list(set(queryset))

def delete_blog_post(request, slug):
    blog_post = get_object_or_404(BlogPost, slug=slug)
    # perform some validation, 
    # like can this user delete this post or not, etc.
    # if validation is successful, delete the article
    blog_post.delete()
    return HttpResponseRedirect('/')

# def timezones_view(request):

#     tzname = pytz.timezone("Europe/Berlin")
#     timezone.activate(pytz.timezone(tzname))

#     render(request, 'blog')

blog/templates/blog/blog_details.html
{% extends 'base.html' %}
{% block title %} Blog Details {% endblock title %}

{% block content %}
<style>
    .container {
        color: #333;
    }

    .header {
        margin-bottom: 20px;
    }

    .card {
        max-width: 900px;
        min-width: 200px;
        /* margin: 0 auto; */
    }

    .container {
        padding: 20px;
    }

    .rightside-posts {
        position: absolute;
        right: 20px;
        top: 80px;
    }

    .delete {
        position: absolute;
        right: 10px;
        padding: 7px 10px;
    }

    .card-page {
        width: 50vw;
    }

    @media (max-width: 396px) {
        .update {
            margin-bottom: 20px;
        }

        .delete {
            display: block;
            margin-top: -15px;
            margin-bottom: 10px;
            left: 30px;
            width: fit-content;
        }
    }

    @media (max-width: 991px) {
    .rightside-posts {
        display: none;
    }

    .footer {
        margin-top: 0;
    }

    .card-page {
        width: 90vw;
        margin: 0 auto;
        /* background-color: red; */
    }
    }

    @media (min-width: 992px) {
        .footer {
        clear: both;
        position: relative;
        margin-top: 400px;
    }

    }
</style>

<div class="parent" style="margin-top: 10rem;margin-bottom: 20rem;">
    <div class="container">
        <div class="row">
            <div class="card card-page py-3 mt-2 col-lg-9">
                {% if blog_details.image %}
                <img src="{{blog_details.image.url}}" class="card-img-top">
                {% endif %}
                <p class="text-muted px-3 pt-3">
                    Updated on {{blog_details.date_updated}} by {{blog_details.author|title}}
                </p>
                <div class="card-body">
                  <h1 class="card-title">{{blog_details.title}}</h1>
                  <p class="card-text">{{blog_details.body|safe}}</p>
                    {% if blog_details.author == request.user %}
                    <a href="{% url 'blog:update_blog_post' blog_details.slug %}" class="update btn btn-primary">Update Blog Post</a>
                    <a href="{% url 'blog:delete_blog_post' blog_details.slug %}" class="delete btn" style="background-color: red;color: #fff;border: none;">Delete Blog Post</a>
                    {% endif %}
                </div>
              </div>
        </div>
    </div>
    <div>
        {% include 'blog/snippets/blog_side_posts_snippet.html' %}
    </div>
    
</div>
{% endblock content %}

blog/templates/blog/create_blog.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Create Post{% endblock title %}

{% block content %}
    <style type="text/css">
        
        .header {
            margin-bottom: 20px;
        }
        .create-form {
            width: 100%;
            max-width: 100%;
            padding: 15px;
            margin: auto;
            }
    
            .submit-button{
                max-width: 200px;
            }

            .form-group {
                margin-bottom: 20px;
            }

            .logo {
                margin-top: 0px;
            }

            #id_image {
                width: 250px;
            }
    </style>
    
    <div class="container">
        <div class="row">
            <div class="col-lg-7 offset-lg-1">
                {% if success_message %}
				    <h3 style="color:#155724; text-align: center;background-color: #D4EDDA;width: 100%;">{{success_message}}</h3>
			    {% endif %}

                <form class="create-form" method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <!-- title -->
                    <div class="form-group">
                        <label for="id_title">Title</label>
                        <input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
                    </div>
    
                    <!-- Body -->
                    <div class="form-group">
                        <label for="id_body">Content</label>
                        {{ create_blog_form.media }}
                        <div style="font-style: normal;">{{ create_blog_form.body }}</div>
                    </div>
    
                    <!-- Image -->
                    <div class="form-group">
                        <label for="id_image">Image</label>
                        <input  type="file" name="image" id="id_image" accept="image/*">
                    </div>
    
                    <!-- Submit btn -->
                    <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
                </form>	
            </div>
        </div>
    </div>

{% endblock content %}

blog/templates/blog/edit_blog_post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Update Blog Post {% endblock title %}

{% block content %}
<style type="text/css">
    .header {
            margin-bottom: 20px;
    }

    label {
        font-weight: bold;
    }
   .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
          display: block;
  	}

	.image {
	  opacity: 1;
	  transition: .5s ease;
	  backface-visibility: hidden;
	}

	.middle {
	  transition: .5s ease;
	  opacity: 0;
	  position: absolute;
	  text-align: center;
	  top: 50%;
	  left: 50%;
	  transform: translate(-50%, -50%);
	
	}
	.image-group{
		position: relative;
  		text-align: center;
  		cursor:pointer;
	}

	.image-group:hover .image {
	  opacity: 0.3;
	}

	.image-group:hover .middle {
	  opacity: 1;
	}

	.text {
	  margin: auto;
	  background-color: #4CAF50;
	  color: white;
	  font-size: 15px;
	  padding: 15px;
	}
</style>

<div class="container">
	<b>
        <a href="{% url 'blog:blog_details' blog_post.slug %}" style="margin-top: -20px;" class="text-decoration-none text-white">Go to Blog Post</a>
    </b>
    
    <div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 class="mt-5" style="color:#155724; text-align: center;background-color: #D4EDDA;width: 100%;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">
                {% csrf_token %}

				<!-- title -->
				<div class="form-group mb-3">
					<label for="id_title">Title</label>
					<input class="form-control mt-2" type="text" name="title" id="id_title" placeholder="Title" value="{{blog_post.title}}" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group mb-3">
					<label for="id_body">Body</label>
					<!-- <> -->
                        
                        <p value="{{blog_post.body}}">
                            {{ update_form.media }}
                            {{ update_form.body }} 
                        </p>
                        
				</div>

				<!-- Image -->
				<label for="id_image_display">Image</label>
                <div class="form-group mb-3 mt-1 image-group" id="id_image_group">
					{% if blog_post.image %}
                        <img class="img-fluid image" src="{{blog_post.image.url}}" id="id_image_display">
                    {% endif %}
					  <div class="middle">
					    <div class="text">Change image</div>
					  </div>
				</div>
				<input class="mt-3" type="file" name="image" id="id_image_file" accept="image/*">
				

				{% for field in form %}
					<p>
						{% for error in field.errors %}
							<p style="color: red">{{ error }}</p>
						{% endfor %}
					</p>
				{% endfor %}
				{% if form.non_field_errors %}
					<div style="color: red">
						<p>{{form.non_field_errors}}</p>
					</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-inline-block my-3" type="submit">Update</button>
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

    // To preview the image chosen
	id_image_file.onchange = evt => {
    const [file] = id_image_file.files
    if (file) {
        id_image_display.src = URL.createObjectURL(file)
    }
    }
</script>

{% endblock content %}