blog/urls.py
from django.urls import re_path, path
from .views import (
    create_blog_view, blog_details_view,
    update_blog_post_view, delete_blog_post
    )

app_name = 'blog'

urlpatterns = [
    re_path(r'^create_post/$', create_blog_view, name="create_blog_post"),
    path('<slug>/', blog_details_view, name="blog_details"),
    path('<slug>/edit', update_blog_post_view, name="update_blog_post"),
    path('<slug>/delete', delete_blog_post, name="delete_blog_post"),
]

blog_app/views.py
from django.shortcuts import render
from operator import attrgetter
from blog.models import BlogPost
from blog.views import get_blog_queryset
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
def home_page(request):
    context = {}
    
    query = ""
    if request.GET:
        query = request.GET.get('query', '')
        context['query'] = str(query)

    blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True) # Sorts the blog post by their dates, here the latest/newest blog posts will comr first in the list.

    # Pagination
    page_number = request.GET.get('page', 1)
    blog_posts_paginator = Paginator(blog_posts, 5) # Shows 5 blog posts per page
    # try:
    blog_posts = blog_posts_paginator.get_page(page_number)
    # except PageNotAnInteger:
    #     blog_posts = blog_posts_paginator.page(BLOG_POST_PER_PAGE)
    # except EmptyPage:
    #     blog_posts = blog_posts_paginator.get_page(blog_posts_paginator.num_pages)
    blog_posts2 = BlogPost.objects.all().order_by('?')[:3]
    context['blog_posts'] = blog_posts
    context['blog_posts2'] = blog_posts2
    return render(request, 'blog_app/home.html', context)

blog_app/templates/blog_app/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home{% endblock title %}
{% block content %}
<style type="text/css">
    .container {
        /* margin: 0; */
        padding: 20px;
    }

    .no-italics {
        font-style: normal;
    }
	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
        /* width: 700px; */
        /* min-width: 200px; */
        /* max-width: 800px; */
	}
	.lead{
		font-size: 17px;;
	}

    .right-blogs-feeds {
        position: absolute;
        top: 35rem;
        width: 25vw;
        right: 10px;
    }
    @media (max-width: 991px) { 
		.right-column{
			margin-left: 0px;
            display: none;
		}
/* 
        .middle {
            margin: 0 auto;
            margin-left: -10px;
        }

        .left-colum {
            margin-left: -10px;
        } */
	}

	@media (min-width: 992px) { 
		.right-column{
			/* margin-left: 20px; */
            position: absolute;
            right: 20px;
            top: 40px
		}
        .left-column {
            margin-left: -200px;
        }
	}
    
</style>



<!-- main content -->
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3 mt-5 p-1">
				<div class="card d-flex flex-column p-2 top-create mx-auto" style="width: 90vw;">
                    <p class="text-center no-italics">
                        <b>Bloggie</b>
                         is a blogging website for people who want to write and people who are into short-form or long-form and image-focused content.</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create_blog_post' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->


			<div class="mt-4 middle">
                <!-- Blog posts-->
                {% if not request.GET.query %}
                {% for post in blog_posts %}
                    <div class="blog-post-container">
                        {% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
                    </div>
                {% endfor %}
                {% else %}
                <div class="blog-post-container">
                    {% include 'blog/snippets/blog_post_snippet.html' with query=query %}
                </div>
                {% endif %}
                <!-- End Blog posts-->

		<!-- Pagination -->
		{% include 'blog/snippets/blog_posts_pagination_snippet.html' with blog_posts=blog_posts %}

		</div>
		<!-- end blog feed -->
	</div>
    <!-- Right 'create post' column  -->
    <div class="right-column col-lg-3 d-lg-flex d-none flex-column mt-4">

        <div class="card create-post-bar d-flex flex-column p-2" style="border-radius: 10px;width: 25vw;box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;right: 30px;">
            <img class="img-fluid d-block m-auto p-2" src="{% static 'index2.jpg' %}" width="100%" height="72px">
            <p class="bg-succes text-center no-italics p-2">
                <b>Bloggie</b>
                is a blogging website for people who want to write and people who are into short-form or long-form and image-focused content.</p>
            <p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create_blog_post' %}">Create post</a></p>
        </div>
    
        <div class="right-blogs-feeds">
            <!-- <h3 style="color: #374150;width: 100%;margin-left: 30px;white-space: nowrap;">You might be interested in</h3> -->
            {% include 'blog/snippets/blog_side_posts_snippet.html' with blog_post=blog_posts2%}
        </div>
    </div>
    <!-- end Right 'create post' column  -->
</div>
</div>

{% endblock content %}